---
layout: post
title:  O que dá para fazer com tanto dinheiro assim?
published: true
tags: [câmara, senado, remuneração]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(screenshot.force = FALSE, echo = FALSE, fig.cap = "")
library(dplyr)
library(devtools)
library(DT)
library(highcharter)
library(knitr)
library(magick)
library(readr)
library(reshape2)
require(scales)
```


```{r pre_processing, include=FALSE}
topSalarios <- function(salariosAgregados, column_ref, keeps, size) {
  topSalarios <- salariosAgregados[order(column_ref, decreasing=TRUE)[1:size],]
  rownames(topSalarios) <- NULL
  colnames(topSalarios) <- keeps
  return(topSalarios)
}

teto_constitucional <- 37476.93

#######################################################################################################
#SENADO
#######################################################################################################
data_filename = "../../_data/dados_senado.csv"
data <- read.csv2(file=data_filename, sep=",", header=FALSE, stringsAsFactors=FALSE, na.strings="unknown", dec=".")
colnames(data) <-  c("id","nome","vinculo","situacao","ano_de_admissao","cargo","padrao","especialidade","mes","ano","remuneracao_basica","vantagens_pessoais","funcao_comissao","gratificacao_natalina","horas_extras","outras_remuneracoes","adicional_periculosidade","adicional_noturno","abono_permanencia","reversao","imposto_de_renda","psss","faltas","remuneracao_apos_descontos","diarias","auxilios","auxilio_alimentacao","vantagens_indenizatorias","adicional_ferias","ferias_indenizatorias","licenca_premio","remuneracao_basica_s","vantagens_pessoais_s","funcao_comissao_s","gratificacao_natalina_s","horas_extras_s","outras_remuneracoes_s","adicional_periculosidade_s","adicional_noturno_s","abono_permanencia_s","reversao_s","imposto_de_renda_s","psss_s","faltas_s","remuneracao_apos_descontos_s","diarias_s","auxilios_s","auxilio_alimentacao_s","vantagens_indenizatorias_s","adicional_ferias_s","ferias_indenizatorias_s","licenca_premio_s")

data <- mutate(data, remuneracao_total=remuneracao_basica + vantagens_pessoais + funcao_comissao + gratificacao_natalina + horas_extras + outras_remuneracoes + abono_permanencia + reversao + imposto_de_renda + psss + faltas + diarias + auxilios + vantagens_indenizatorias)
data <- mutate(data, remuneracao_total_s=remuneracao_basica_s + vantagens_pessoais_s + funcao_comissao_s + gratificacao_natalina_s + horas_extras_s + outras_remuneracoes_s + abono_permanencia_s + reversao_s + imposto_de_renda_s + psss_s + faltas_s + diarias_s + auxilios_s + vantagens_indenizatorias_s)
data <- mutate(data, remuneracao_total_liquida=remuneracao_total+remuneracao_total_s)

ano_max <- max(data$ano)
ano_min <- min(data$ano)

senado_recente <- data[data$ano==ano_max,]
remuneracao_total_liquida <- sum(data$remuneracao_total_liquida, na.rm=T)

keeps <- c("Nome","Cargo","Especialidade","Situação","Mês","Ano","Ano de Admissão","Licença-Prêmio* (R$)")
salariosAgregados <- aggregate(licenca_premio_s~nome+cargo+especialidade+situacao+mes+ano+ano_de_admissao, FUN=sum, senado_recente)
top_servidores_licenca_premio <- topSalarios(salariosAgregados, salariosAgregados$licenca_premio_s, keeps, 10)
gastos_licenca_premio <- sum(top_servidores_licenca_premio$`Licença-Prêmio* (R$)`)

senado_ano_anterior <- data[data$ano==ano_max-1,]
aposentados_senado_ano_anterior <- senado_ano_anterior[senado_ano_anterior$situacao=="APOSENTADO", ]

#######################################################################################################
#CÂMARA
#######################################################################################################
data_filename = "../../_data/camara_dados.txt"
data_c <- read.csv2(file=data_filename, sep=",", header=FALSE, stringsAsFactors=FALSE, na.strings="unknown", dec=".", encoding = "UTF-8")
colnames(data_c) <-  c("mes","ano","cargo","vinculo","nome","remuneracao_fixa","vantagens_pessoais","remuneracao_eventual","abono_permanencia","descontos","diarias","outros_auxilios","outras_vantagens")

data_c <- mutate(data_c, remuneracao_total=remuneracao_fixa+vantagens_pessoais+remuneracao_eventual+abono_permanencia-descontos+diarias+outros_auxilios+outras_vantagens)

ano_max_c <- max(data_c$ano)
ano_min_c <- min(data_c$ano)

keeps <- c("Nome","Cargo","Vnculo","Mês","Ano","Remuneração Total (R$)")
salariosAgregados <- aggregate(remuneracao_total~nome+cargo+vinculo+mes+ano, FUN=sum, data_c)
top_servidores_todos_c <- topSalarios(salariosAgregados, salariosAgregados$remuneracao_total, keeps, 10)

todos_servidores_recente_c <- data_c[data_c$ano==ano_max_c,]

remuneracao_total_c <- sum(top_servidores_todos_c$`Remuneração Total (R$)`)

todos_deputados <- filter(data_c, grepl("DEPUTADO", cargo))
todos_deputados_recente <- todos_deputados[todos_deputados$ano==ano_max_c,]

remuneracao_total_c <- sum(data_c$remuneracao_total)
remuneracao_recente_c <- sum(todos_servidores_recente_c$remuneracao_total)
remuneracao_deputados <- sum(todos_deputados$remuneracao_total)
remuneracao_deputados_recente <- sum(todos_deputados_recente$remuneracao_total)

keeps <- c("Nome","Mês","Ano","Remuneração Total (R$)")
salariosAgregados <- aggregate(remuneracao_total~nome+mes+ano, FUN=sum, todos_deputados)
top_deputados_todos <- topSalarios(salariosAgregados, salariosAgregados$remuneracao_total, keeps, 10)

salariosAgregados <- aggregate(remuneracao_total~nome+mes+ano, FUN=sum, todos_deputados_recente)
top_deputados_recente <- topSalarios(salariosAgregados, salariosAgregados$remuneracao_total, keeps, 10)

teto_constitucional <- 37476.93

todos_deputados_ano_anterior <- todos_deputados[todos_deputados$ano==ano_max_c-1,]
salariosAgregados <- aggregate(remuneracao_total~nome, FUN=sum, todos_deputados_ano_anterior)
keeps <- c("Nome","Remuneração Total (R$)")
top_deputados_ano_anterior <- topSalarios(salariosAgregados, salariosAgregados$remuneracao_total, keeps, 10)

todos_servidores_ano_anterior_c <- data_c[data_c$ano==ano_max_c-1,]
todos_servidores_ano_anterior <- data_c[data_c$ano==ano_max_c-1,]
gasto_do_senado_e_camara_ano_anterior <-sum(todos_servidores_ano_anterior_c$remuneracao_total)+sum(todos_servidores_ano_anterior$remuneracao_total_liquida)


```

```{r capes, echo=FALSE}
  frink <- image_read("../../_data/capes.jpeg")
custo <- 2200
texto <- paste("A REMUNERAÇÃO DE TODOS OS\nDEPUTADOS EM", ano_max_c, "É O\nSUFICIENTE PARA PAGAR", floor(remuneracao_deputados_recente/(custo*48)), "ALUNOS\nDE DOUTORADO POR 4 ANOS!")
image <- image_annotate(frink, texto, size = 50, gravity = "center", strokecolor="black", color = "white", font='../../_data/Impact.ttf')
plot(image)
```

```{r samu, echo=FALSE}
frink <- image_read("../../_data/samu.jpg")
custo <- 150000
texto <- paste("O PAGAMENTO DE LICENÇA-PRÊMIO\nAOS DEZ SERVIDORES MAIS\nBENEFICIADOS EM", ano_max,"DA PARA\nADQUIRIR", floor(gastos_licenca_premio/custo), "AMBULÂNCIAS!")
image <- image_annotate(frink, texto, size = 70, gravity = "center", strokecolor="black", color = "white", font='../../_data/Impact.ttf')
plot(image)
```

```{r empregado, echo=FALSE}
frink <- image_read("../../_data/empregado-domestico.jpg")
custo <- 120
texto <- paste("A REMUNERAÇÃO TOTAL DO DEPUTADO\n", top_deputados_ano_anterior[1,]$Nome, "\nNO ANO DE", ano_max-1, "É EQUIVALENTE A\nCONTRIBUIÇÃO DE", floor(top_deputados_ano_anterior[1,]$`Remuneração Total (R$)`/(custo*12)), "EMPREGADOS(AS)\nDOMÉSTICOS(AS) AO INSS POR UM ANO!")
image <- image_annotate(frink, texto, size = 80, gravity = "center", strokecolor="black", color = "white", font='../../_data/Impact.ttf')
plot(image)
```

```{r hospital, echo=FALSE}
frink <- image_read("../../_data/hospital.jpg")
custo <- 8525928.52 
texto <- paste("A FOLHA DE PAGAMENTO DA CÂMARA\nE DO SENADO PARA O ANO", ano_max-1, "\nDARIA PARA CONSTRUIR", floor(gasto_do_senado_e_camara_ano_anterior/custo), "HOSPITAIS!")
image <- image_annotate(frink, texto, size = 50, gravity = "center", strokecolor="black", color = "white", font='../../_data/Impact.ttf')
plot(image)
```

```{r brasilia, echo=FALSE}
frink <- image_read("../../_data/brasilia.jpg")
texto <- paste("EM", ano_max-1, ", A FOLHA DE PAGAMENTO DA CÂMARA\nE DO SENADO FOI DE R$", round(gasto_do_senado_e_camara_ano_anterior/10^9, 1), "BILHÕES!\n")
texto <- paste(texto, "\nR$", round(gasto_do_senado_e_camara_ano_anterior/(365*10^6), 1), "MILHÕES por dia!" )
texto <- paste(texto, "\nR$", round(gasto_do_senado_e_camara_ano_anterior/(365*24*10^3), 1), "MIL por hora!" )
texto <- paste(texto, "\nR$", round(gasto_do_senado_e_camara_ano_anterior/(365*24*60*10^3), 1), "MIL por minuto!" )
texto <- paste(texto, "\nR$", round(gasto_do_senado_e_camara_ano_anterior/(365*24*60*60), 1), "por segundo!" )
image <- image_annotate(frink, texto, size = 90, gravity = "center", strokecolor="black", color = "white", font='../../_data/Impact.ttf')
plot(image)
```

```{r neymar, echo=FALSE}
frink <- image_read("../../_data/neymar.jpeg")
custo <- 110*10^6
texto <- paste("EM", ano_max-1,", SÓ A FOLHA DE PAGAMENTO\nPARA APOSENTADOS DO SENADO,\nDARIA PARA CONTRATAR\nNEYMAR POR", floor(sum(aposentados_senado_ano_anterior$remuneracao_total_liquida)/custo), "ANOS!")
image <- image_annotate(frink, texto, size = 30, gravity = "center", strokecolor="black", color = "white", location='+0+80', font='../../_data/Impact.ttf')
plot(image)
```
