---
layout: post
title:  Quanto que os Deputados Receberam nas Votações
published: true
tags: [câmara, emendas parlamentares, impeachment]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(screenshot.force = FALSE, echo = FALSE, fig.cap = "")
library(dplyr)
library(devtools)
library(DT)
library(flexdashboard)
library(highcharter)
library(knitr)
library(ggplot2)
library(rCharts)
library(readr)
library(reshape2)
require(scales)
library(shiny)
library(plotly)
```


```{r pre_processing, include=FALSE}
data_filename_dilma_vs_temer="../../_data/camara_dilma_vs_temer.csv"
data_dilma_temer <- read.csv2(file=data_filename_dilma_vs_temer, header=TRUE, sep=";", stringsAsFactors=FALSE, na.strings="unknown", dec=".", encoding = "UTF-8")
```

```{r votacao_temer}
#############################################################
# Imprimindo Relação de Emendas com votos à Temer           #
#############################################################
mean_temer_pagos <- aggregate(emendas_pagas~voto_temer, FUN=mean, data=data_dilma_temer)
mean_temer_prometidos <- aggregate(emendas_prometidas~voto_temer, FUN=mean, data=data_dilma_temer)
mean_temer <- cbind(mean_temer_pagos, mean_temer_prometidos$emendas_prometidas)
colnames(mean_temer) <- c("Voto Temer", "Emendas Pagas (R$)", "Emendas Prometidas (R$)")
mean_temer$`Emendas Pagas (R$)` <- round(mean_temer$`Emendas Pagas (R$)`, 1)
mean_temer$`Emendas Prometidas (R$)` <- round(mean_temer$`Emendas Prometidas (R$)`, 1)
datatable(mean_temer, options = list(paging=F,info=F,searching=F), rownames=FALSE) %>%
  formatCurrency('Emendas Pagas (R$)',currency = "", interval = 3, mark = ",") %>%
  formatCurrency('Emendas Prometidas (R$)',currency = "", interval = 3, mark = ",")
```

```{r votacao_impeachment_dilma}
############################################################
# Imprimindo Relação de Emendas com votos ao impeachment   #
############################################################
mean_dilma_pagos <- aggregate(emendas_pagas~impeachment_dilma, FUN=mean, data=data_dilma_temer)
mean_dilma_prometidos <- aggregate(emendas_prometidas~impeachment_dilma, FUN=mean, data=data_dilma_temer)
mean_dilma <- cbind(mean_dilma_pagos, mean_dilma_prometidos$emendas_prometidas)
colnames(mean_dilma) <- c("Voto Dilma", "Emendas Pagas (R$)", "Emendas Prometidas (R$)")
mean_dilma$`Emendas Pagas (R$)` <- round(mean_dilma$`Emendas Pagas (R$)`, 1)
mean_dilma$`Emendas Prometidas (R$)` <- round(mean_dilma$`Emendas Prometidas (R$)`, 1)
datatable(mean_dilma, options = list(paging=F,info=F,searching=F), rownames=FALSE) %>%
  formatCurrency('Emendas Pagas (R$)',currency = "", interval = 3, mark = ",") %>%
  formatCurrency('Emendas Prometidas (R$)',currency = "", interval = 3, mark = ",")
```

